export const timeFrame = [
    {ac: '1', ta: '1m', value: "1m", label: '1 minute'},
    {ac: '3', ta: '3m', value: "3m", label: '3 minutes'},
    {ac: '5', ta: '5m', value: "5m", label: '5 minutes'},
    {ac: '15', ta: '15m', value: "15m",label: '15 minutes'},
    {ac: '30', ta: '30m', value: "30m",label: '30 minutes'},
    {ac: '60', ta: '1h', value: "1h", label: '1 hour'},
    {ac: '120', ta: '2h', value: "2h", label: '2 hours'},
    {ac: '240', ta: '4h', value: "4h", label: '4 hours'},
    // {ac: '', ta: '6h', value: "6h", label: '6 hours'},
    // {ac: '1', ta: '8h', value: "8h", label: '8 hours'},
    // {ac: '1', ta: '12h', value: "12h",label: '12 hours'},
    {ac: 'D', ta: '1D', value: "1d", label: '1 day'},
    // {ac: '1', ta: '3D', value: "3d", label: '3 days'},
    {ac: 'W', ta: '1W', value: "1w", label: '1 week'},
    // {ac: '1', ta: '1M', value: "1M", label: "1 month"},
];
//
// export const timeFrame = ['1 minute',
// '3 minutes',
// '5 minutes',
//  '15 minutes',
//'30 minutes',
// '1 hour',
// '2 hours',
// '4 hours',
// '6 hours',
// '8 hours',
//  '12 hours',
// '1 day',
// '3 days',
// '1 week',
// "1 month"]
